const DATA = [
  // ---------------- Navigation & Structure ----------------
  {cat:"Navigation & Structure", concept:"Top bar with title & actions", demo:"navbar",
    ios:{term:"Navigation Bar", fw:"UINavigationBar · NavigationStack toolbar"},
    android:{term:"Top App Bar", fw:"Toolbar · TopAppBar"},
    desc:"Persistent bar at the top of a screen holding a title, back control, and one or two primary actions."},
  {cat:"Navigation & Structure", concept:"Bottom tab navigation", demo:"tabbar",
    ios:{term:"Tab Bar", fw:"UITabBar · TabView"},
    android:{term:"Bottom Navigation", fw:"BottomNavigationView · NavigationBar"},
    desc:"Fixed set of top-level destinations (3–5 items) always visible at the bottom of the screen."},
  {cat:"Navigation & Structure", concept:"Slide-out side menu", demo:"drawer",
    ios:{term:"No native component", fw:"custom-built, rarely used on iOS", none:true},
    android:{term:"Navigation Drawer", fw:"DrawerLayout · ModalNavigationDrawer"},
    desc:"A panel of navigation destinations that slides in from the edge. Common on Android, discouraged by Apple's HIG."},
  {cat:"Navigation & Structure", concept:"Going back a screen", demo:"backrow",
    ios:{term:"Back button + edge-swipe gesture", fw:"UINavigationController pop"},
    android:{term:"Back button / system back gesture", fw:"OnBackPressedCallback · predictive back"},
    desc:"iOS relies on an explicit back button plus a swipe-from-left-edge gesture; Android has a system-level back gesture/button that any screen must handle."},
  {cat:"Navigation & Structure", concept:"Row of switchable sub-views", demo:"segmented",
    ios:{term:"Segmented Control", fw:"UISegmentedControl · Picker(.segmented)"},
    android:{term:"Tabs", fw:"TabLayout · TabRow"},
    desc:"A small set of mutually exclusive options shown as a single connected control, typically switching content below it."},
  {cat:"Navigation & Structure", concept:"Pushing a new screen onto a stack", demo:"stacknav",
    ios:{term:"Push (Navigation Controller)", fw:"UINavigationController.pushViewController"},
    android:{term:"Navigate to a destination", fw:"NavController.navigate() · Fragment transaction"},
    desc:"Moving forward in a linear flow, adding the new screen on top with an animated transition and a way back."},

  // ---------------- Buttons & Actions ----------------
  {cat:"Buttons & Actions", concept:"Standard tappable button", demo:"button",
    ios:{term:"Button", fw:"UIButton · Button"},
    android:{term:"Button", fw:"MaterialButton · Button"},
    desc:"The basic control for a single tap action. Both platforms define filled, outlined, and text/plain styles."},
  {cat:"Buttons & Actions", concept:"Circular primary-action button", demo:"fab",
    ios:{term:"No standard component", fw:"custom circular button", none:true},
    android:{term:"Floating Action Button (FAB)", fw:"FloatingActionButton"},
    desc:"A circular button, usually bottom-right, for the screen's single most important action. A core Material pattern; iOS has no equivalent convention."},
  {cat:"Buttons & Actions", concept:"Overflow / \"more\" menu", demo:"overflow",
    ios:{term:"Ellipsis Button / Menu", fw:"UIMenu on a UIButton"},
    android:{term:"Overflow Menu", fw:"three-dot icon → PopupMenu / DropdownMenu"},
    desc:"A button (··· on iOS, ⋮ on Android) that reveals secondary actions that don't fit in the main bar."},
  {cat:"Buttons & Actions", concept:"Long-press contextual menu", demo:"contextmenu",
    ios:{term:"Context Menu", fw:"UIContextMenuInteraction · contextMenu()"},
    android:{term:"Context Menu", fw:"registerForContextMenu · long-press + DropdownMenu"},
    desc:"A menu of actions relevant to a specific item, triggered by a long press (iOS often pairs it with a preview/peek)."},
  {cat:"Buttons & Actions", concept:"Swipe-to-reveal row actions", demo:"swipe",
    ios:{term:"Swipe Actions", fw:"leadingSwipeActions / trailingSwipeActions"},
    android:{term:"Swipe to Dismiss/Reveal", fw:"ItemTouchHelper · SwipeToDismissBox"},
    desc:"Actions (e.g. delete, archive) revealed by swiping a list row left or right."},

  // ---------------- Input & Selection ----------------
  {cat:"Input & Selection", concept:"Single-line text input", demo:"textfield",
    ios:{term:"Text Field", fw:"UITextField · TextField"},
    android:{term:"Edit Text", fw:"EditText · TextField (Material)"},
    desc:"The base control for typed text entry. Android's Material version bundles a floating label by default."},
  {cat:"Input & Selection", concept:"Multi-line text input", demo:"textarea",
    ios:{term:"Text View", fw:"UITextView · TextEditor"},
    android:{term:"Multiline Edit Text", fw:"EditText(inputType=multiline)"},
    desc:"A scrollable text field for paragraphs — comments, notes, descriptions."},
  {cat:"Input & Selection", concept:"On/off toggle", demo:"switch",
    ios:{term:"Switch", fw:"UISwitch · Toggle"},
    android:{term:"Switch", fw:"SwitchCompat · Switch"},
    desc:"A binary control shown as a sliding pill. Both platforms style it near-identically."},
  {cat:"Input & Selection", concept:"Checkbox", demo:"checkbox",
    ios:{term:"No native checkbox", fw:"custom, or a Toggle in checkbox style", none:true},
    android:{term:"Checkbox", fw:"CheckBox · Checkbox"},
    desc:"Multi-select square control. Standard on Android; Apple's HIG doesn't define one for iPhone (it does on macOS)."},
  {cat:"Input & Selection", concept:"Single choice from a list", demo:"radio",
    ios:{term:"Checkmark in grouped list rows", fw:"custom UITableView pattern"},
    android:{term:"Radio Button", fw:"RadioButton · RadioButtonGroup"},
    desc:"Mutually-exclusive selection. Android has a dedicated Radio Button; iOS convention is a checkmark on the selected row of a grouped table."},
  {cat:"Input & Selection", concept:"Scrollable value picker", demo:"picker",
    ios:{term:"Picker", fw:"UIPickerView · Picker(.wheel)"},
    android:{term:"Spinner / Dropdown Menu", fw:"Spinner · ExposedDropdownMenu"},
    desc:"Choosing one value from a set. iOS favors a spinning wheel; Android favors a dropdown/menu-style selector."},
  {cat:"Input & Selection", concept:"Date / time selection", demo:"datepicker",
    ios:{term:"Date Picker", fw:"UIDatePicker · DatePicker"},
    android:{term:"Date Picker / Time Picker", fw:"MaterialDatePicker · DatePicker (Compose)"},
    desc:"Both platforms provide a dedicated, system-styled date/time selection surface, usually shown in a sheet or dialog."},
  {cat:"Input & Selection", concept:"Continuous range input", demo:"slider",
    ios:{term:"Slider", fw:"UISlider · Slider"},
    android:{term:"Slider", fw:"Slider (Material)"},
    desc:"Dragging a thumb along a track to choose a value in a range, e.g. volume or brightness."},
  {cat:"Input & Selection", concept:"Small increment/decrement control", demo:"stepper",
    ios:{term:"Stepper", fw:"UIStepper · Stepper"},
    android:{term:"No direct equivalent", fw:"custom +/- buttons", none:true},
    desc:"A tiny plus/minus control for adjusting a small numeric value, e.g. item quantity."},
  {cat:"Input & Selection", concept:"Search input", demo:"searchbar",
    ios:{term:"Search Bar", fw:"UISearchBar · .searchable()"},
    android:{term:"Search Bar / SearchView", fw:"SearchView · SearchBar (Compose)"},
    desc:"A dedicated text field for querying content, usually docked at the top and often revealed on scroll or tap."},

  // ---------------- Lists & Collections ----------------
  {cat:"Lists & Collections", concept:"Vertical scrolling list", demo:"list",
    ios:{term:"Table View", fw:"UITableView · List"},
    android:{term:"Recycler View", fw:"RecyclerView · LazyColumn"},
    desc:"The workhorse scrolling list of rows, with cell/view recycling for performance on both platforms."},
  {cat:"Lists & Collections", concept:"Grid of items", demo:"grid",
    ios:{term:"Collection View", fw:"UICollectionView · LazyVGrid"},
    android:{term:"Grid List", fw:"RecyclerView (GridLayoutManager) · LazyVerticalGrid"},
    desc:"A scrolling grid layout, typically for photos, products, or tiles."},
  {cat:"Lists & Collections", concept:"Elevated content container", demo:"card",
    ios:{term:"Card (convention, not a class)", fw:"custom rounded-corner view"},
    android:{term:"Card", fw:"MaterialCardView · Card"},
    desc:"A contained, often-elevated block grouping related content. Android formalizes this as a component; iOS treats it as a visual pattern."},
  {cat:"Lists & Collections", concept:"Pull down to reload content", demo:"refresh",
    ios:{term:"Refresh Control", fw:"UIRefreshControl · .refreshable()"},
    android:{term:"Swipe Refresh", fw:"SwipeRefreshLayout · pullRefresh"},
    desc:"Dragging a list down past its top reveals a spinner and triggers a data reload."},
  {cat:"Lists & Collections", concept:"Sticky section headers", demo:"sticky",
    ios:{term:"Section header/footer (grouped style)", fw:"UITableView section headers"},
    android:{term:"Sticky Header", fw:"RecyclerView sticky decoration · LazyColumn stickyHeader"},
    desc:"A header that remains pinned at the top of the viewport while its section's rows scroll underneath."},

  // ---------------- Overlays & Sheets ----------------
  {cat:"Overlays & Sheets", concept:"Blocking dialog with message + buttons", demo:"alert",
    ios:{term:"Alert", fw:"UIAlertController(.alert) · .alert()"},
    android:{term:"Dialog / Alert Dialog", fw:"AlertDialog"},
    desc:"A centered, modal dialog interrupting the flow to confirm or inform, with 1–3 buttons."},
  {cat:"Overlays & Sheets", concept:"List of actions from the bottom", demo:"actionsheet",
    ios:{term:"Action Sheet", fw:"UIAlertController(.actionSheet) · .confirmationDialog()"},
    android:{term:"Bottom Sheet (modal, action list)", fw:"BottomSheetDialog"},
    desc:"A set of actions related to the current context, presented as a list sliding up from the bottom edge."},
  {cat:"Overlays & Sheets", concept:"Draggable partial-height panel", demo:"sheet",
    ios:{term:"Sheet (with detents)", fw:".sheet() · UISheetPresentationController"},
    android:{term:"Bottom Sheet (persistent/standard)", fw:"BottomSheetBehavior · ModalBottomSheet"},
    desc:"A panel that can be dragged between fixed heights (peek, half, full) while the underlying screen stays visible."},
  {cat:"Overlays & Sheets", concept:"Small anchored popup", demo:"popover",
    ios:{term:"Popover", fw:"UIPopoverPresentationController · .popover()"},
    android:{term:"Popup Window / Dropdown Menu", fw:"PopupWindow · DropdownMenu"},
    desc:"A small floating panel anchored to the control that triggered it, common on iPad; on phone iOS often substitutes a sheet."},
  {cat:"Overlays & Sheets", concept:"Full-screen temporary flow", demo:"fullscreen",
    ios:{term:"Full-Screen Cover / Modal", fw:".fullScreenCover() · modalPresentationStyle"},
    android:{term:"Full-Screen Dialog Fragment", fw:"DialogFragment (fullscreen theme)"},
    desc:"A screen presented on top of the current context, covering it entirely, typically for a self-contained task like composing or onboarding."},

  // ---------------- Feedback & Status ----------------
  {cat:"Feedback & Status", concept:"Brief auto-dismissing message", demo:"toast",
    ios:{term:"No native equivalent", fw:"custom toast/HUD (e.g. UIAlertController hacks)", none:true},
    android:{term:"Toast", fw:"Toast.makeText()"},
    desc:"A short, unobtrusive message that appears briefly and disappears on its own, with no action. Native and idiomatic on Android; recreated manually on iOS."},
  {cat:"Feedback & Status", concept:"Message with an action button", demo:"snackbar",
    ios:{term:"Custom banner", fw:"no direct system component", none:true},
    android:{term:"Snackbar", fw:"Snackbar.make()"},
    desc:"Similar to a toast but can include a single action (e.g. \"Undo\"), typically anchored to the bottom of the screen."},
  {cat:"Feedback & Status", concept:"Indeterminate loading spinner", demo:"activityindicator",
    ios:{term:"Activity Indicator", fw:"UIActivityIndicatorView · ProgressView()"},
    android:{term:"Circular Progress Indicator", fw:"ProgressBar (circular) · CircularProgressIndicator"},
    desc:"A spinning indicator shown while work of unknown duration happens in the background."},
  {cat:"Feedback & Status", concept:"Determinate progress bar", demo:"progress",
    ios:{term:"Progress View", fw:"UIProgressView · ProgressView(value:)"},
    android:{term:"Linear Progress Indicator", fw:"ProgressBar (horizontal) · LinearProgressIndicator"},
    desc:"A horizontal bar filling to show percentage completion of a known-length task."},
  {cat:"Feedback & Status", concept:"Small numeric/status marker", demo:"badge",
    ios:{term:"Badge", fw:"UITabBarItem.badgeValue · notification badge"},
    android:{term:"Badge", fw:"BadgeDrawable · Badge (Compose)"},
    desc:"A small dot or number overlaid on an icon to indicate unread count or status."},
  {cat:"Feedback & Status", concept:"Physical tap feedback", demo:"haptic",
    ios:{term:"Haptic Feedback", fw:"UIFeedbackGenerator"},
    android:{term:"Haptic Feedback", fw:"View.performHapticFeedback() · HapticFeedback"},
    desc:"Short vibration/tactile response confirming an interaction. iOS has a richer, more standardized haptic vocabulary (light/medium/heavy, success/warning/error)."},

  // ---------------- System Chrome & Layout ----------------
  {cat:"System Chrome & Layout", concept:"Device status area (clock, signal, battery)", demo:"statusbar",
    ios:{term:"Status Bar", fw:"UIStatusBar"},
    android:{term:"Status Bar", fw:"System status bar"},
    desc:"The strip at the very top of the screen owned by the OS, showing time and system icons."},
  {cat:"System Chrome & Layout", concept:"Region to avoid device notches/bars", demo:"safearea",
    ios:{term:"Safe Area", fw:"safeAreaLayoutGuide · .safeAreaInset()"},
    android:{term:"Window Insets", fw:"WindowInsets · systemBarsPadding()"},
    desc:"The layout guide that keeps content clear of notches, status bars, and home indicators/navigation bars."},
  {cat:"System Chrome & Layout", concept:"Bottom system gesture/button area", demo:"homeindicator",
    ios:{term:"Home Indicator", fw:"bottom safe-area inset"},
    android:{term:"Navigation Bar (gesture or 3-button)", fw:"navigationBars insets"},
    desc:"The reserved strip at the bottom of the screen for returning home / going back, whose height content should respect."},
  {cat:"System Chrome & Layout", concept:"Stacking views in a row/column", demo:"stack",
    ios:{term:"Stack View / SwiftUI stacks", fw:"UIStackView · VStack, HStack, ZStack"},
    android:{term:"Linear Layout / Compose stacks", fw:"LinearLayout · Column, Row, Box"},
    desc:"The basic layout primitive for arranging child views linearly or overlapping."},
  {cat:"System Chrome & Layout", concept:"Constraint-based layout", demo:"constraints",
    ios:{term:"Auto Layout", fw:"NSLayoutConstraint"},
    android:{term:"Constraint Layout", fw:"ConstraintLayout"},
    desc:"Positioning views via relationships/constraints to siblings and the parent, rather than fixed coordinates."},
  {cat:"System Chrome & Layout", concept:"Depth via shadow vs. surface elevation", demo:"depth",
    ios:{term:"Shadow (flat design, used sparingly)", fw:"CALayer.shadow*"},
    android:{term:"Elevation", fw:"View.elevation · Modifier.shadow()"},
    desc:"Both express depth with shadow, but Material treats elevation as a literal, systematic z-axis value; iOS uses shadow more sparingly and less formally."},
  {cat:"System Chrome & Layout", concept:"Dark color scheme", demo:"darkmode",
    ios:{term:"Dark Mode", fw:"traitCollection.userInterfaceStyle"},
    android:{term:"Dark Theme", fw:"Configuration.uiMode · isSystemInDarkTheme()"},
    desc:"A system-wide dark color palette that apps should adapt to automatically."},

  // ---------------- Design Language & Frameworks ----------------
  {cat:"Design Language & Frameworks", concept:"Official design guidelines", demo:"guideline",
    ios:{term:"Human Interface Guidelines (HIG)", fw:"developer.apple.com/design"},
    android:{term:"Material Design (Material 3)", fw:"m3.material.io"},
    desc:"The canonical rulebook each platform publishes — the vocabulary in this sheet is drawn from both."},
  {cat:"Design Language & Frameworks", concept:"Modern declarative UI framework", demo:"declarative",
    ios:{term:"SwiftUI", fw:"declarative, since 2019"},
    android:{term:"Jetpack Compose", fw:"declarative, since 2021"},
    desc:"The current-generation, state-driven UI toolkit on each platform, gradually replacing the imperative one below."},
  {cat:"Design Language & Frameworks", concept:"Legacy imperative UI framework", demo:"imperative",
    ios:{term:"UIKit", fw:"imperative, view-controller based"},
    android:{term:"Views / Android View System", fw:"imperative, XML layouts + Activities/Fragments"},
    desc:"The older, still widely-used toolkit most existing production codebases are built on."},
];

const CATEGORY_ORDER = [...new Set(DATA.map(d => d.cat))];
