const DATA = [
  // ---------------- Navigation & Structure ----------------
  {cat:"Navigation & Structure", concept:"Top bar with title & actions", demo:"navbar",
    ios:{term:"Navigation Bar", fw:[{t:"UINavigationBar", url:"https://developer.apple.com/documentation/uikit/uinavigationbar"},{t:"NavigationStack toolbar", url:"https://developer.apple.com/documentation/swiftui/navigationstack"}]},
    android:{term:"Top App Bar", fw:[{t:"Toolbar", url:"https://developer.android.com/reference/androidx/appcompat/widget/Toolbar"},{t:"TopAppBar", url:"https://developer.android.com/develop/ui/compose/components/app-bars"}]},
    desc:"Persistent bar at the top of a screen holding a title, back control, and one or two primary actions."},
  {cat:"Navigation & Structure", concept:"Bottom tab navigation", demo:"tabbar",
    ios:{term:"Tab Bar", fw:[{t:"UITabBar", url:"https://developer.apple.com/documentation/uikit/uitabbar"},{t:"TabView", url:"https://developer.apple.com/documentation/swiftui/tabview"}]},
    android:{term:"Bottom Navigation", fw:[{t:"BottomNavigationView", url:"https://developer.android.com/reference/com/google/android/material/bottomnavigation/BottomNavigationView"},{t:"NavigationBar", url:"https://developer.android.com/develop/ui/compose/components/navigation-bar"}]},
    desc:"Fixed set of top-level destinations (3–5 items) always visible at the bottom of the screen."},
  {cat:"Navigation & Structure", concept:"Slide-out side menu", demo:"drawer",
    ios:{term:"No native component", fw:"custom-built, rarely used on iOS", none:true},
    android:{term:"Navigation Drawer", fw:[{t:"DrawerLayout", url:"https://developer.android.com/reference/androidx/drawerlayout/widget/DrawerLayout"},{t:"ModalNavigationDrawer", url:"https://developer.android.com/develop/ui/compose/components/drawer"}]},
    desc:"A panel of navigation destinations that slides in from the edge. Common on Android, discouraged by Apple's HIG."},
  {cat:"Navigation & Structure", concept:"Going back a screen", demo:"backrow",
    ios:{term:"Back button + edge-swipe gesture", fw:[{t:"UINavigationController pop", url:"https://developer.apple.com/documentation/uikit/uinavigationcontroller"}]},
    android:{term:"Back button / system back gesture", fw:[{t:"OnBackPressedCallback", url:"https://developer.android.com/reference/androidx/activity/OnBackPressedCallback"},{t:"predictive back", url:"https://developer.android.com/guide/navigation/predictive-back-gesture"}]},
    desc:"iOS relies on an explicit back button plus a swipe-from-left-edge gesture; Android has a system-level back gesture/button that any screen must handle."},
  {cat:"Navigation & Structure", concept:"Row of switchable sub-views", demo:"segmented",
    ios:{term:"Segmented Control", fw:[{t:"UISegmentedControl", url:"https://developer.apple.com/documentation/uikit/uisegmentedcontrol"},{t:"Picker(.segmented)", url:"https://developer.apple.com/documentation/swiftui/picker"}]},
    android:{term:"Tabs", fw:[{t:"TabLayout", url:"https://developer.android.com/reference/com/google/android/material/tabs/TabLayout"},{t:"TabRow", url:"https://developer.android.com/develop/ui/compose/components/tabs"}]},
    desc:"A small set of mutually exclusive options shown as a single connected control, typically switching content below it."},
  {cat:"Navigation & Structure", concept:"Pushing a new screen onto a stack", demo:"stacknav",
    ios:{term:"Push (Navigation Controller)", fw:[{t:"UINavigationController.pushViewController", url:"https://developer.apple.com/documentation/uikit/uinavigationcontroller"}]},
    android:{term:"Navigate to a destination", fw:[{t:"NavController.navigate()", url:"https://developer.android.com/reference/kotlin/androidx/navigation/NavController"},{t:"Fragment transaction", url:"https://developer.android.com/guide/fragments/transactions"}]},
    desc:"Moving forward in a linear flow, adding the new screen on top with an animated transition and a way back."},
  {cat:"Navigation & Structure", concept:"Presenting a screen modally", demo:"modalpresent",
    ios:{term:"Modal Presentation", fw:[{t:"present(animated:)", url:"https://developer.apple.com/documentation/uikit/uiviewcontroller"},{t:".sheet() / .fullScreenCover()", url:"https://developer.apple.com/documentation/swiftui/view"}]},
    android:{term:"Dialog Destination", fw:[{t:"NavGraphBuilder.dialog()", url:"https://developer.android.com/reference/kotlin/androidx/navigation/NavGraphBuilder"},{t:"DialogFragment", url:"https://developer.android.com/reference/androidx/fragment/app/DialogFragment"}]},
    desc:"A new screen floats over the current one as an interruption to be explicitly dismissed, rather than being pushed into the back stack for linear back-navigation."},

  // ---------------- Buttons & Actions ----------------
  {cat:"Buttons & Actions", concept:"Standard tappable button", demo:"button",
    ios:{term:"Button", fw:[{t:"UIButton", url:"https://developer.apple.com/documentation/uikit/uibutton"},{t:"Button", url:"https://developer.apple.com/documentation/swiftui/button"}]},
    android:{term:"Button", fw:[{t:"MaterialButton", url:"https://developer.android.com/reference/com/google/android/material/button/MaterialButton"},{t:"Button", url:"https://developer.android.com/develop/ui/compose/components/button"}]},
    desc:"The basic control for a single tap action. Both platforms define filled, outlined, and text/plain styles."},
  {cat:"Buttons & Actions", concept:"Circular primary-action button", demo:"fab",
    ios:{term:"No standard component", fw:"custom circular button", none:true},
    android:{term:"Floating Action Button (FAB)", fw:[{t:"FloatingActionButton", url:"https://developer.android.com/reference/com/google/android/material/floatingactionbutton/FloatingActionButton"}]},
    desc:"A circular button, usually bottom-right, for the screen's single most important action. A core Material pattern; iOS has no equivalent convention."},
  {cat:"Buttons & Actions", concept:"Action button on the top bar", demo:"actionbutton",
    ios:{term:"Bar Button Item", fw:[{t:"UIBarButtonItem", url:"https://developer.apple.com/documentation/uikit/uibarbuttonitem"},{t:"ToolbarItem", url:"https://developer.apple.com/documentation/swiftui/toolbaritem"}]},
    android:{term:"Action Item", fw:[{t:"MenuItem (showAsAction)", url:"https://developer.android.com/reference/android/view/MenuItem"},{t:"TopAppBar actions", url:"https://developer.android.com/develop/ui/compose/components/app-bars"}]},
    desc:"A tappable icon placed directly in the top bar for a primary action (e.g. save, search). Actions that don't fit collapse into the overflow menu below."},
  {cat:"Buttons & Actions", concept:"Overflow / \"more\" menu", demo:"overflow",
    ios:{term:"Ellipsis Button / Menu", fw:[{t:"UIMenu on a UIButton", url:"https://developer.apple.com/documentation/uikit/uimenu"}]},
    android:{term:"Overflow Menu", fw:[{t:"three-dot icon → PopupMenu / DropdownMenu"}]},
    desc:"A button (··· on iOS, ⋮ on Android) that reveals secondary actions that don't fit in the main bar."},
  {cat:"Buttons & Actions", concept:"Long-press contextual menu", demo:"contextmenu",
    ios:{term:"Context Menu", fw:[{t:"UIContextMenuInteraction", url:"https://developer.apple.com/documentation/uikit/uicontextmenuinteraction"},{t:"contextMenu()"}]},
    android:{term:"Context Menu", fw:[{t:"registerForContextMenu", url:"https://developer.android.com/reference/android/view/View"},{t:"long-press + DropdownMenu", url:"https://developer.android.com/develop/ui/compose/components/menu"}]},
    desc:"A menu of actions relevant to a specific item, triggered by a long press (iOS often pairs it with a preview/peek)."},
  {cat:"Buttons & Actions", concept:"Swipe-to-reveal row actions", demo:"swipe",
    ios:{term:"Swipe Actions", fw:[{t:"leadingSwipeActions / trailingSwipeActions"}]},
    android:{term:"Swipe to Dismiss/Reveal", fw:[{t:"ItemTouchHelper", url:"https://developer.android.com/reference/androidx/recyclerview/widget/ItemTouchHelper"},{t:"SwipeToDismissBox"}]},
    desc:"Actions (e.g. delete, archive) revealed by swiping a list row left or right."},

  // ---------------- Input & Selection ----------------
  {cat:"Input & Selection", concept:"Single-line text input", demo:"textfield",
    ios:{term:"Text Field", fw:[{t:"UITextField", url:"https://developer.apple.com/documentation/uikit/uitextfield"},{t:"TextField", url:"https://developer.apple.com/documentation/swiftui/textfield"}]},
    android:{term:"Edit Text", fw:[{t:"EditText", url:"https://developer.android.com/reference/android/widget/EditText"},{t:"TextField (Material)", url:"https://developer.android.com/develop/ui/compose/text/user-input"}]},
    desc:"The base control for typed text entry. Android's Material version bundles a floating label by default."},
  {cat:"Input & Selection", concept:"Multi-line text input", demo:"textarea",
    ios:{term:"Text View", fw:[{t:"UITextView", url:"https://developer.apple.com/documentation/uikit/uitextview"},{t:"TextEditor", url:"https://developer.apple.com/documentation/swiftui/texteditor"}]},
    android:{term:"Multiline Edit Text", fw:[{t:"EditText(inputType=multiline)", url:"https://developer.android.com/reference/android/widget/EditText"}]},
    desc:"A scrollable text field for paragraphs — comments, notes, descriptions."},
  {cat:"Input & Selection", concept:"On/off toggle", demo:"switch",
    ios:{term:"Switch", fw:[{t:"UISwitch", url:"https://developer.apple.com/documentation/uikit/uiswitch"},{t:"Toggle", url:"https://developer.apple.com/documentation/swiftui/toggle"}]},
    android:{term:"Switch", fw:[{t:"SwitchCompat", url:"https://developer.android.com/reference/androidx/appcompat/widget/SwitchCompat"},{t:"Switch", url:"https://developer.android.com/develop/ui/compose/components/switch"}]},
    desc:"A binary control shown as a sliding pill. Both platforms style it near-identically."},
  {cat:"Input & Selection", concept:"Checkbox", demo:"checkbox",
    ios:{term:"No native checkbox", fw:"custom, or a Toggle in checkbox style", none:true},
    android:{term:"Checkbox", fw:[{t:"CheckBox", url:"https://developer.android.com/reference/android/widget/CheckBox"},{t:"Checkbox", url:"https://developer.android.com/develop/ui/compose/components/checkbox"}]},
    desc:"Multi-select square control. Standard on Android; Apple's HIG doesn't define one for iPhone (it does on macOS)."},
  {cat:"Input & Selection", concept:"Single choice from a list", demo:"radio",
    ios:{term:"Checkmark in grouped list rows", fw:[{t:"custom UITableView pattern", url:"https://developer.apple.com/documentation/uikit/uitableview"}]},
    android:{term:"Radio Button", fw:[{t:"RadioButton", url:"https://developer.android.com/reference/android/widget/RadioButton"},{t:"RadioButtonGroup", url:"https://developer.android.com/develop/ui/compose/components/radio-button"}]},
    desc:"Mutually-exclusive selection. Android has a dedicated Radio Button; iOS convention is a checkmark on the selected row of a grouped table."},
  {cat:"Input & Selection", concept:"Scrollable value picker", demo:"picker",
    ios:{term:"Picker", fw:[{t:"UIPickerView", url:"https://developer.apple.com/documentation/uikit/uipickerview"},{t:"Picker(.wheel)", url:"https://developer.apple.com/documentation/swiftui/picker"}]},
    android:{term:"Spinner / Dropdown Menu", fw:[{t:"Spinner", url:"https://developer.android.com/reference/android/widget/Spinner"},{t:"ExposedDropdownMenu", url:"https://developer.android.com/develop/ui/compose/components/menu"}]},
    desc:"Choosing one value from a set. iOS favors a spinning wheel; Android favors a dropdown/menu-style selector."},
  {cat:"Input & Selection", concept:"Date / time selection", demo:"datepicker",
    ios:{term:"Date Picker", fw:[{t:"UIDatePicker", url:"https://developer.apple.com/documentation/uikit/uidatepicker"},{t:"DatePicker", url:"https://developer.apple.com/documentation/swiftui/datepicker"}]},
    android:{term:"Date Picker / Time Picker", fw:[{t:"MaterialDatePicker", url:"https://developer.android.com/reference/com/google/android/material/datepicker/MaterialDatePicker"},{t:"DatePicker (Compose)", url:"https://developer.android.com/develop/ui/compose/components/datepickers"}]},
    desc:"Both platforms provide a dedicated, system-styled date/time selection surface, usually shown in a sheet or dialog."},
  {cat:"Input & Selection", concept:"Continuous range input", demo:"slider",
    ios:{term:"Slider", fw:[{t:"UISlider", url:"https://developer.apple.com/documentation/uikit/uislider"},{t:"Slider", url:"https://developer.apple.com/documentation/swiftui/slider"}]},
    android:{term:"Slider", fw:[{t:"Slider (Material)", url:"https://developer.android.com/develop/ui/compose/components/slider"}]},
    desc:"Dragging a thumb along a track to choose a value in a range, e.g. volume or brightness."},
  {cat:"Input & Selection", concept:"Small increment/decrement control", demo:"stepper",
    ios:{term:"Stepper", fw:[{t:"UIStepper", url:"https://developer.apple.com/documentation/uikit/uistepper"},{t:"Stepper", url:"https://developer.apple.com/documentation/swiftui/stepper"}]},
    android:{term:"No direct equivalent", fw:"custom +/- buttons", none:true},
    desc:"A tiny plus/minus control for adjusting a small numeric value, e.g. item quantity."},
  {cat:"Input & Selection", concept:"Search input", demo:"searchbar",
    ios:{term:"Search Bar", fw:[{t:"UISearchBar", url:"https://developer.apple.com/documentation/uikit/uisearchbar"},{t:".searchable()", url:"https://developer.apple.com/documentation/swiftui/view"}]},
    android:{term:"Search Bar / SearchView", fw:[{t:"SearchView", url:"https://developer.android.com/reference/androidx/appcompat/widget/SearchView"},{t:"SearchBar (Compose)", url:"https://developer.android.com/develop/ui/compose/components/search-bar"}]},
    desc:"A dedicated text field for querying content, usually docked at the top and often revealed on scroll or tap."},

  // ---------------- Lists & Collections ----------------
  {cat:"Lists & Collections", concept:"Vertical scrolling list", demo:"list",
    ios:{term:"Table View", fw:[{t:"UITableView", url:"https://developer.apple.com/documentation/uikit/uitableview"},{t:"List", url:"https://developer.apple.com/documentation/swiftui/list"}]},
    android:{term:"Recycler View", fw:[{t:"RecyclerView", url:"https://developer.android.com/reference/androidx/recyclerview/widget/RecyclerView"},{t:"LazyColumn", url:"https://developer.android.com/develop/ui/compose/lists"}]},
    desc:"The workhorse scrolling list of rows, with cell/view recycling for performance on both platforms."},
  {cat:"Lists & Collections", concept:"Grid of items", demo:"grid",
    ios:{term:"Collection View", fw:[{t:"UICollectionView", url:"https://developer.apple.com/documentation/uikit/uicollectionview"},{t:"LazyVGrid", url:"https://developer.apple.com/documentation/swiftui/lazyvgrid"}]},
    android:{term:"Grid List", fw:[{t:"RecyclerView (GridLayoutManager)", url:"https://developer.android.com/reference/androidx/recyclerview/widget/GridLayoutManager"},{t:"LazyVerticalGrid", url:"https://developer.android.com/develop/ui/compose/lists"}]},
    desc:"A scrolling grid layout, typically for photos, products, or tiles."},
  {cat:"Lists & Collections", concept:"Elevated content container", demo:"card",
    ios:{term:"Card (convention, not a class)", fw:[{t:"custom rounded-corner view"}]},
    android:{term:"Card", fw:[{t:"MaterialCardView", url:"https://developer.android.com/reference/com/google/android/material/card/MaterialCardView"},{t:"Card", url:"https://developer.android.com/develop/ui/compose/components/card"}]},
    desc:"A contained, often-elevated block grouping related content. Android formalizes this as a component; iOS treats it as a visual pattern."},
  {cat:"Lists & Collections", concept:"Pull down to reload content", demo:"refresh",
    ios:{term:"Refresh Control", fw:[{t:"UIRefreshControl", url:"https://developer.apple.com/documentation/uikit/uirefreshcontrol"},{t:".refreshable()", url:"https://developer.apple.com/documentation/swiftui/view"}]},
    android:{term:"Swipe Refresh", fw:[{t:"SwipeRefreshLayout", url:"https://developer.android.com/reference/androidx/swiperefreshlayout/widget/SwipeRefreshLayout"},{t:"pullRefresh"}]},
    desc:"Dragging a list down past its top reveals a spinner and triggers a data reload."},
  {cat:"Lists & Collections", concept:"Sticky section headers", demo:"sticky",
    ios:{term:"Section header/footer (grouped style)", fw:[{t:"UITableView section headers", url:"https://developer.apple.com/documentation/uikit/uitableview"}]},
    android:{term:"Sticky Header", fw:[{t:"RecyclerView sticky decoration", url:"https://developer.android.com/reference/androidx/recyclerview/widget/RecyclerView"},{t:"LazyColumn stickyHeader", url:"https://developer.android.com/develop/ui/compose/lists"}]},
    desc:"A header that remains pinned at the top of the viewport while its section's rows scroll underneath."},

  // ---------------- Media & Content ----------------
  {cat:"Media & Content", concept:"Displaying an image", demo:"imageview",
    ios:{term:"Image View", fw:[{t:"UIImageView", url:"https://developer.apple.com/documentation/uikit/uiimageview"},{t:"Image", url:"https://developer.apple.com/documentation/swiftui/image"}]},
    android:{term:"Image View", fw:[{t:"ImageView", url:"https://developer.android.com/reference/android/widget/ImageView"},{t:"Image (Compose)", url:"https://developer.android.com/develop/ui/compose/graphics/images/customize"}]},
    desc:"The standard view for rendering a bitmap/vector image, with content-mode / scale-type options for cropping, fitting, or filling its bounds."},
  {cat:"Media & Content", concept:"Embedding web content", demo:"webview",
    ios:{term:"Web View", fw:[{t:"WKWebView", url:"https://developer.apple.com/documentation/webkit/wkwebview"},{t:"WebView (WebKit, iOS 18.4+)", url:"https://developer.apple.com/documentation/webkit/webkit-for-swiftui"}]},
    android:{term:"WebView", fw:[{t:"WebView", url:"https://developer.android.com/reference/android/webkit/WebView"},{t:"AndroidView(WebView) in Compose", url:"https://developer.android.com/develop/ui/compose/migrate/interoperability-apis/wrap-webview-in-compose"}]},
    desc:"Renders HTML/web content inside a native screen. Both platforms wrap a system browser engine (WebKit / Chromium WebView) rather than reimplementing one; Compose has no built-in WebView and wraps the classic View."},

  // ---------------- Overlays & Sheets ----------------
  {cat:"Overlays & Sheets", concept:"Blocking dialog with message + buttons", demo:"alert",
    ios:{term:"Alert", fw:[{t:"UIAlertController(.alert)", url:"https://developer.apple.com/documentation/uikit/uialertcontroller"},{t:".alert()", url:"https://developer.apple.com/documentation/swiftui/view"}]},
    android:{term:"Dialog / Alert Dialog", fw:[{t:"AlertDialog", url:"https://developer.android.com/reference/android/app/AlertDialog"}]},
    desc:"A centered, modal dialog interrupting the flow to confirm or inform, with 1–3 buttons."},
  {cat:"Overlays & Sheets", concept:"List of actions from the bottom", demo:"actionsheet",
    ios:{term:"Action Sheet", fw:[{t:"UIAlertController(.actionSheet)", url:"https://developer.apple.com/documentation/uikit/uialertcontroller"},{t:".confirmationDialog()", url:"https://developer.apple.com/documentation/swiftui/view"}]},
    android:{term:"Bottom Sheet (modal, action list)", fw:[{t:"BottomSheetDialog", url:"https://developer.android.com/reference/com/google/android/material/bottomsheet/BottomSheetDialog"}]},
    desc:"A set of actions related to the current context, presented as a list sliding up from the bottom edge."},
  {cat:"Overlays & Sheets", concept:"Draggable partial-height panel", demo:"sheet",
    ios:{term:"Sheet (with detents)", fw:[{t:".sheet()", url:"https://developer.apple.com/documentation/swiftui/view"},{t:"UISheetPresentationController", url:"https://developer.apple.com/documentation/uikit/uisheetpresentationcontroller"}]},
    android:{term:"Bottom Sheet (persistent/standard)", fw:[{t:"BottomSheetBehavior", url:"https://developer.android.com/reference/com/google/android/material/bottomsheet/BottomSheetBehavior"},{t:"ModalBottomSheet", url:"https://developer.android.com/develop/ui/compose/components/bottom-sheets"}]},
    desc:"A panel that can be dragged between fixed heights (peek, half, full) while the underlying screen stays visible."},
  {cat:"Overlays & Sheets", concept:"Small anchored popup", demo:"popover",
    ios:{term:"Popover", fw:[{t:"UIPopoverPresentationController", url:"https://developer.apple.com/documentation/uikit/uipopoverpresentationcontroller"},{t:".popover()", url:"https://developer.apple.com/documentation/swiftui/view"}]},
    android:{term:"Popup Window / Dropdown Menu", fw:[{t:"PopupWindow", url:"https://developer.android.com/reference/android/widget/PopupWindow"},{t:"DropdownMenu", url:"https://developer.android.com/develop/ui/compose/components/menu"}]},
    desc:"A small floating panel anchored to the control that triggered it, common on iPad; on phone iOS often substitutes a sheet."},
  {cat:"Overlays & Sheets", concept:"Full-screen temporary flow", demo:"fullscreen",
    ios:{term:"Full-Screen Cover / Modal", fw:[{t:".fullScreenCover()", url:"https://developer.apple.com/documentation/swiftui/view"},{t:"modalPresentationStyle", url:"https://developer.apple.com/documentation/uikit/uiviewcontroller"}]},
    android:{term:"Full-Screen Dialog Fragment", fw:[{t:"DialogFragment (fullscreen theme)", url:"https://developer.android.com/reference/androidx/fragment/app/DialogFragment"}]},
    desc:"A screen presented on top of the current context, covering it entirely, typically for a self-contained task like composing or onboarding."},

  // ---------------- Feedback & Status ----------------
  {cat:"Feedback & Status", concept:"Brief auto-dismissing message", demo:"toast",
    ios:{term:"No native equivalent", fw:"custom toast/HUD (e.g. UIAlertController hacks)", none:true},
    android:{term:"Toast", fw:[{t:"Toast.makeText()", url:"https://developer.android.com/reference/android/widget/Toast"}]},
    desc:"A short, unobtrusive message that appears briefly and disappears on its own, with no action. Native and idiomatic on Android; recreated manually on iOS."},
  {cat:"Feedback & Status", concept:"Message with an action button", demo:"snackbar",
    ios:{term:"Custom banner", fw:"no direct system component", none:true},
    android:{term:"Snackbar", fw:[{t:"Snackbar.make()", url:"https://developer.android.com/reference/com/google/android/material/snackbar/Snackbar"}]},
    desc:"Similar to a toast but can include a single action (e.g. \"Undo\"), typically anchored to the bottom of the screen."},
  {cat:"Feedback & Status", concept:"Indeterminate loading spinner", demo:"activityindicator",
    ios:{term:"Activity Indicator", fw:[{t:"UIActivityIndicatorView", url:"https://developer.apple.com/documentation/uikit/uiactivityindicatorview"},{t:"ProgressView()", url:"https://developer.apple.com/documentation/swiftui/progressview"}]},
    android:{term:"Circular Progress Indicator", fw:[{t:"ProgressBar (circular)", url:"https://developer.android.com/reference/android/widget/ProgressBar"},{t:"CircularProgressIndicator", url:"https://developer.android.com/develop/ui/compose/components/progress"}]},
    desc:"A spinning indicator shown while work of unknown duration happens in the background."},
  {cat:"Feedback & Status", concept:"Determinate progress bar", demo:"progress",
    ios:{term:"Progress View", fw:[{t:"UIProgressView", url:"https://developer.apple.com/documentation/uikit/uiprogressview"},{t:"ProgressView(value:)", url:"https://developer.apple.com/documentation/swiftui/progressview"}]},
    android:{term:"Linear Progress Indicator", fw:[{t:"ProgressBar (horizontal)", url:"https://developer.android.com/reference/android/widget/ProgressBar"},{t:"LinearProgressIndicator", url:"https://developer.android.com/develop/ui/compose/components/progress"}]},
    desc:"A horizontal bar filling to show percentage completion of a known-length task."},
  {cat:"Feedback & Status", concept:"Small numeric/status marker", demo:"badge",
    ios:{term:"Badge", fw:[{t:"UITabBarItem.badgeValue", url:"https://developer.apple.com/documentation/uikit/uitabbaritem"},{t:"notification badge"}]},
    android:{term:"Badge", fw:[{t:"BadgeDrawable", url:"https://developer.android.com/reference/com/google/android/material/badge/BadgeDrawable"},{t:"Badge (Compose)", url:"https://developer.android.com/develop/ui/compose/components/badges"}]},
    desc:"A small dot or number overlaid on an icon to indicate unread count or status."},
  {cat:"Feedback & Status", concept:"Physical tap feedback", demo:"haptic",
    ios:{term:"Haptic Feedback", fw:[{t:"UIFeedbackGenerator", url:"https://developer.apple.com/documentation/uikit/uifeedbackgenerator"}]},
    android:{term:"Haptic Feedback", fw:[{t:"View.performHapticFeedback()", url:"https://developer.android.com/reference/android/view/View"},{t:"HapticFeedback", url:"https://developer.android.com/reference/kotlin/androidx/compose/ui/hapticfeedback/HapticFeedback"}]},
    desc:"Short vibration/tactile response confirming an interaction. iOS has a richer, more standardized haptic vocabulary (light/medium/heavy, success/warning/error)."},

  // ---------------- System Chrome & Layout ----------------
  {cat:"System Chrome & Layout", concept:"Device status area (clock, signal, battery)", demo:"statusbar",
    ios:{term:"Status Bar", fw:[{t:"UIStatusBar", url:"https://developer.apple.com/design/human-interface-guidelines/status-bars"}]},
    android:{term:"Status Bar", fw:[{t:"System status bar"}]},
    desc:"The strip at the very top of the screen owned by the OS, showing time and system icons."},
  {cat:"System Chrome & Layout", concept:"Region to avoid device notches/bars", demo:"safearea",
    ios:{term:"Safe Area", fw:[{t:"safeAreaLayoutGuide", url:"https://developer.apple.com/documentation/uikit/uiview"},{t:".safeAreaInset()", url:"https://developer.apple.com/documentation/swiftui/view"}]},
    android:{term:"Window Insets", fw:[{t:"WindowInsets", url:"https://developer.android.com/reference/androidx/core/view/WindowInsetsCompat"},{t:"systemBarsPadding()"}]},
    desc:"The layout guide that keeps content clear of notches, status bars, and home indicators/navigation bars."},
  {cat:"System Chrome & Layout", concept:"Bottom system gesture/button area", demo:"homeindicator",
    ios:{term:"Home Indicator", fw:[{t:"bottom safe-area inset", url:"https://developer.apple.com/documentation/uikit/uiview"}]},
    android:{term:"Navigation Bar (gesture or 3-button)", fw:[{t:"navigationBars insets", url:"https://developer.android.com/reference/androidx/core/view/WindowInsetsCompat"}]},
    desc:"The reserved strip at the bottom of the screen for returning home / going back, whose height content should respect."},
  {cat:"System Chrome & Layout", concept:"Stacking views in a row/column", demo:"stack",
    ios:{term:"Stack View / SwiftUI stacks", fw:[{t:"UIStackView", url:"https://developer.apple.com/documentation/uikit/uistackview"},{t:"VStack, HStack, ZStack", url:"https://developer.apple.com/documentation/swiftui/vstack"}]},
    android:{term:"Linear Layout / Compose stacks", fw:[{t:"LinearLayout", url:"https://developer.android.com/reference/android/widget/LinearLayout"},{t:"Column, Row, Box", url:"https://developer.android.com/develop/ui/compose/layouts/basics"}]},
    desc:"The basic layout primitive for arranging child views linearly or overlapping."},
  {cat:"System Chrome & Layout", concept:"Constraint-based layout", demo:"constraints",
    ios:{term:"Auto Layout", fw:[{t:"NSLayoutConstraint", url:"https://developer.apple.com/documentation/uikit/nslayoutconstraint"}]},
    android:{term:"Constraint Layout", fw:[{t:"ConstraintLayout", url:"https://developer.android.com/reference/androidx/constraintlayout/widget/ConstraintLayout"}]},
    desc:"Positioning views via relationships/constraints to siblings and the parent, rather than fixed coordinates."},
  {cat:"System Chrome & Layout", concept:"Thin line separating content", demo:"divider",
    ios:{term:"Divider", fw:[{t:"UITableView separator", url:"https://developer.apple.com/documentation/uikit/uitableview"},{t:"Divider()", url:"https://developer.apple.com/documentation/swiftui/divider"}]},
    android:{term:"Divider", fw:[{t:"MaterialDivider", url:"https://developer.android.com/reference/com/google/android/material/divider/MaterialDivider"},{t:"HorizontalDivider/VerticalDivider (Compose)", url:"https://developer.android.com/develop/ui/compose/components/divider"}]},
    desc:"A thin rule separating grouped content. SwiftUI and Compose both offer a dedicated component; UIKit typically relies on the built-in list-row separator instead of a standalone view."},
  {cat:"System Chrome & Layout", concept:"Depth via shadow vs. surface elevation", demo:"depth",
    ios:{term:"Shadow (flat design, used sparingly)", fw:[{t:"CALayer.shadow*", url:"https://developer.apple.com/documentation/quartzcore/calayer"}]},
    android:{term:"Elevation", fw:[{t:"View.elevation", url:"https://developer.android.com/reference/android/view/View"},{t:"Modifier.shadow()"}]},
    desc:"Both express depth with shadow, but Material treats elevation as a literal, systematic z-axis value; iOS uses shadow more sparingly and less formally."},
  {cat:"System Chrome & Layout", concept:"Dark color scheme", demo:"darkmode",
    ios:{term:"Dark Mode", fw:[{t:"traitCollection.userInterfaceStyle", url:"https://developer.apple.com/documentation/uikit/uitraitcollection"}]},
    android:{term:"Dark Theme", fw:[{t:"Configuration.uiMode", url:"https://developer.android.com/reference/android/content/res/Configuration"},{t:"isSystemInDarkTheme()"}]},
    desc:"A system-wide dark color palette that apps should adapt to automatically."},

  // ---------------- Design Language & Frameworks ----------------
  {cat:"Design Language & Frameworks", concept:"Official design guidelines", demo:"guideline",
    ios:{term:"Human Interface Guidelines (HIG)", fw:[{t:"developer.apple.com/design", url:"https://developer.apple.com/design/"}]},
    android:{term:"Material Design (Material 3)", fw:[{t:"m3.material.io", url:"https://m3.material.io/"}]},
    desc:"The canonical rulebook each platform publishes — the vocabulary in this sheet is drawn from both."},
  {cat:"Design Language & Frameworks", concept:"Modern declarative UI framework", demo:"declarative",
    ios:{term:"SwiftUI", fw:[{t:"declarative, since 2019", url:"https://developer.apple.com/documentation/swiftui"}]},
    android:{term:"Jetpack Compose", fw:[{t:"declarative, since 2021", url:"https://developer.android.com/compose"}]},
    desc:"The current-generation, state-driven UI toolkit on each platform, gradually replacing the imperative one below."},
  {cat:"Design Language & Frameworks", concept:"Legacy imperative UI framework", demo:"imperative",
    ios:{term:"UIKit", fw:[{t:"imperative, view-controller based", url:"https://developer.apple.com/documentation/uikit"}]},
    android:{term:"Views / Android View System", fw:[{t:"imperative, XML layouts + Activities/Fragments", url:"https://developer.android.com/develop/ui/views/layout/declaring-layout"}]},
    desc:"The older, still widely-used toolkit most existing production codebases are built on."},
  {cat:"Design Language & Frameworks", concept:"Icon library", demo:"iconsystem",
    ios:{term:"SF Symbols", fw:[{t:"9,000+ symbols, ships with San Francisco font", url:"https://developer.apple.com/sf-symbols/"}]},
    android:{term:"Material Symbols", fw:[{t:"Apache-2.0, variable font + SVG", url:"https://fonts.google.com/icons"}]},
    desc:"Each platform's canonical icon set. Material Symbols is Apache-2.0 and free to embed anywhere, web included; SF Symbols is licensed only for use inside apps built for Apple's own platforms, not for websites or cross-platform software."},
];

const CATEGORY_ORDER = [...new Set(DATA.map(d => d.cat))];
